apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    service: product
spec:
  replicas: 2
  selector:
    matchLabels:
      service: product
  template:
    metadata:
      labels:
        service: product
    spec:
      containers:
        - name: product
          image: heaves/product-service-single:3.4
          ports:
            - containerPort: 9301
