apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    service: product
spec:
  replicas: 3
  selector:
    matchLabels:
      service: product
  template:
    metadata:
      labels:
        service: product
    spec:
      containers:
        - name: product
          image: heaves/product-service-single:v1.0.57
          ports:
            - containerPort: 9301
